spring:
  datasource:
    url: jdbc:postgresql://192.168.0.29:8000/blog
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 5000

springfox:
  documentation:
    enabled: true